version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./resources/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      testing_net:
        ipv4_address: 172.28.1.5
  
  web:
    image: nginx
    container_name: web
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src
      - ./resources/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  php-fpm:
    build: resources/php-fpm
    container_name: php-fpm
    working_dir: /var/www/src
    volumes:
      - ./src:/var/www/src
      - ./resources/php-fpm/php.ini:/etc/php/7.3/fpm/conf.d/php.ini
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
