version: '3'
services:

    postgres:
      image: "postgres"
      container_name: ${PROJECT_NAME}-postgres
      volumes:
         - "./resources/postgres:/var/lib/postgresql/data"
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
       - "5432:5432"
      networks:
            ${PROJECT_NAME}_net:
                ipv4_address: 172.28.1.2

    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /var/www/${PROJECT_NAME}
      volumes:
          - ./src:/var/www/src
          - ./resources/nginx:/etc/nginx/conf.d
      ports:
       - "80:80"
      networks:
            ${PROJECT_NAME}_net:
                ipv4_address: 172.28.1.3

    php-fpm:
      build: resources/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /var/www/${PROJECT_NAME}
      volumes:
        - ./src:/var/www/src
        - ./resources/php-fpm/php.ini:/etc/php/7.3/fpm/conf.d/php.ini
      networks:
          ${PROJECT_NAME}_net:
              ipv4_address: 172.28.1.4

networks:
    ${PROJECT_NAME}_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
